### ISSUE TITLE
What is the correct parameter for "--model_ckpt"

### ISSUE THREAD

**Issue by JiejiangWu** [msraig/mp_gan#1]
Hi, I have downloaded the pretrained model "pretrain_model.zip". When I want to test it, I was confused what exactly is the input parameter for "--model_ckpt"?

I have tried 'pretrain_model.zip' and a extracted dir  'pretrain_model' from the zip file. But it seems wrong.

**Comment by pableeto** [comment]
The path is the exact tensorflow checkpoint file path for the model you want to test. 
e.g. : "./pretrain_model/chair_syn_32_mirror/model" for pre-trained chair model.
